"""
Build a Kaggle-ready single-file submission.py from local training artifacts.

This script updates only the BUILD_CONFIG block in submission.py:
  # === BUILD_CONFIG_START ===
  ...
  # === BUILD_CONFIG_END ===

Artifacts:
  - agents/weights.py    (Optuna/scalar weights)
  - agents/td_weights.py (TD feature weights)
"""

from __future__ import annotations

import argparse
import runpy
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Dict, List, Optional

BUILD_START_MARKER = "# === BUILD_CONFIG_START ==="
BUILD_END_MARKER = "# === BUILD_CONFIG_END ==="

DEFAULT_W_SCORE = 10.0
DEFAULT_W_THREAT = 100.0
DEFAULT_W_HMAP = 0.3
DEFAULT_W_ODD_EVEN = 80.0
DEFAULT_POSITION_HEATMAP = [
    [3, 4, 5, 7, 5, 4, 3],
    [4, 6, 8, 10, 8, 6, 4],
    [5, 8, 11, 13, 11, 8, 5],
    [5, 8, 11, 13, 11, 8, 5],
    [4, 6, 8, 10, 8, 6, 4],
    [3, 4, 5, 7, 5, 4, 3],
]


@dataclass
class BuildConfig:
    w_score: float = DEFAULT_W_SCORE
    w_threat: float = DEFAULT_W_THREAT
    w_hmap: float = DEFAULT_W_HMAP
    w_odd_even: float = DEFAULT_W_ODD_EVEN
    heatmap: List[List[float]] = None
    td_weights: Optional[List[float]] = None
    source: str = "default"

    def __post_init__(self) -> None:
        if self.heatmap is None:
            self.heatmap = [row[:] for row in DEFAULT_POSITION_HEATMAP]


def _workspace_root() -> Path:
    return Path(__file__).resolve().parents[1]


def _to_float(value: Any, fallback: float) -> float:
    try:
        return float(value)
    except (TypeError, ValueError):
        return float(fallback)


def _parse_heatmap(value: Any) -> Optional[List[List[float]]]:
    if not isinstance(value, (list, tuple)) or len(value) != 6:
        return None
    parsed: List[List[float]] = []
    for row in value:
        if not isinstance(row, (list, tuple)) or len(row) != 7:
            return None
        parsed.append([float(v) for v in row])
    return parsed


def _parse_td_weights(value: Any) -> Optional[List[float]]:
    if value is None:
        return None
    if not isinstance(value, (list, tuple)):
        raise ValueError("TD_WEIGHTS must be a list or tuple")
    if len(value) != 11:
        raise ValueError(f"TD_WEIGHTS must have 11 values, got {len(value)}")
    return [float(v) for v in value]


def _load_python_artifact(path: Path) -> Dict[str, Any]:
    if not path.exists():
        return {}
    return runpy.run_path(str(path))


def _load_optuna_config(path: Path) -> Dict[str, Any]:
    data = _load_python_artifact(path)
    if not data:
        return {}

    w_score = None
    w_threat = None
    if "W_SCORE" in data:
        w_score = data["W_SCORE"]
    if "W_THREAT" in data:
        w_threat = data["W_THREAT"]

    # Backward compatibility with older weights.py format.
    if (w_score is None or w_threat is None) and "WINDOW_WEIGHTS" in data:
        window_weights = data.get("WINDOW_WEIGHTS", [])
        if isinstance(window_weights, (list, tuple)) and len(window_weights) >= 3:
            if w_score is None:
                w_score = window_weights[1]
            if w_threat is None:
                w_threat = window_weights[2]

    return {
        "w_score": w_score,
        "w_threat": w_threat,
        "w_hmap": data.get("W_HMAP"),
        "w_odd_even": data.get("W_ODD_EVEN"),
        "heatmap": data.get("POSITION_HEATMAP"),
    }


def _load_td_config(path: Path) -> Dict[str, Any]:
    data = _load_python_artifact(path)
    if not data:
        return {}
    return {"td_weights": data.get("TD_WEIGHTS")}


def _fmt_number(value: float) -> str:
    v = float(value)
    if v.is_integer():
        return str(int(v))
    return f"{v:.12g}"


def _format_heatmap(heatmap: List[List[float]]) -> str:
    lines = ["["]
    for row in heatmap:
        row_values = ", ".join(_fmt_number(v) for v in row)
        lines.append(f"    [{row_values}],")
    lines.append("]")
    return "\n".join(lines)


def _format_td_weights(td_weights: Optional[List[float]]) -> str:
    if td_weights is None:
        return "None"
    values = ", ".join(_fmt_number(v) for v in td_weights)
    return f"[{values}]"


def render_build_block(config: BuildConfig) -> str:
    heatmap_text = _format_heatmap(config.heatmap)
    td_text = _format_td_weights(config.td_weights)
    return (
        f"{BUILD_START_MARKER}\n"
        f"# Generated by evaluate/build_submission.py. Source: {config.source}\n"
        f"_W_SCORE = {_fmt_number(config.w_score)}\n"
        f"_W_THREAT = {_fmt_number(config.w_threat)}\n"
        f"_W_HMAP = {_fmt_number(config.w_hmap)}\n"
        f"_W_ODD_EVEN = {_fmt_number(config.w_odd_even)}\n"
        f"_HEATMAP = np.array({heatmap_text}, dtype=np.float32)\n"
        f"# Format: [bias, w_2self, w_3self, w_2opp, w_3opp,\n"
        f"#          w_hmap_self, w_hmap_opp,\n"
        f"#          w_odd_self, w_even_self, w_odd_opp, w_even_opp]\n"
        f"_TD_WEIGHTS = {td_text}\n"
        f"{BUILD_END_MARKER}"
    )


def inject_build_block(source_text: str, block_text: str) -> str:
    start = source_text.find(BUILD_START_MARKER)
    end = source_text.find(BUILD_END_MARKER)
    if start < 0 or end < 0 or end < start:
        raise ValueError(
            "submission template missing build markers: "
            f"{BUILD_START_MARKER} ... {BUILD_END_MARKER}"
        )

    end += len(BUILD_END_MARKER)
    return source_text[:start] + block_text + source_text[end:]


def resolve_build_config(
    profile: str = "auto",
    weights_path: Optional[Path] = None,
    td_weights_path: Optional[Path] = None,
) -> BuildConfig:
    root = _workspace_root()
    weights_path = weights_path or (root / "agents" / "weights.py")
    td_weights_path = td_weights_path or (root / "agents" / "td_weights.py")

    config = BuildConfig()
    sources: List[str] = ["defaults"]

    optuna_data = _load_optuna_config(weights_path)
    if optuna_data:
        config.w_score = _to_float(optuna_data.get("w_score"), config.w_score)
        config.w_threat = _to_float(optuna_data.get("w_threat"), config.w_threat)
        config.w_hmap = _to_float(optuna_data.get("w_hmap"), config.w_hmap)
        config.w_odd_even = _to_float(optuna_data.get("w_odd_even"), config.w_odd_even)
        heatmap = _parse_heatmap(optuna_data.get("heatmap"))
        if heatmap is not None:
            config.heatmap = heatmap
        sources.append(str(weights_path))

    td_data = _load_td_config(td_weights_path)
    td_weights = None
    if td_data:
        td_weights = _parse_td_weights(td_data.get("td_weights"))

    if profile == "td":
        if td_weights is None:
            raise ValueError(f"TD profile requested but no TD_WEIGHTS in {td_weights_path}")
        config.td_weights = td_weights
        sources.append(str(td_weights_path))
    elif profile == "optuna":
        config.td_weights = None
    elif profile == "auto":
        if td_weights is not None:
            config.td_weights = td_weights
            sources.append(str(td_weights_path))
        else:
            config.td_weights = None
    else:
        raise ValueError(f"Unsupported profile: {profile}")

    config.source = ", ".join(sources)
    return config


def build_submission_with_config(
    template_path: Path,
    output_path: Path,
    config: BuildConfig,
) -> BuildConfig:
    source_text = template_path.read_text(encoding="utf-8")
    block = render_build_block(config)
    built_text = inject_build_block(source_text, block)
    output_path.write_text(built_text, encoding="utf-8")
    return config


def build_submission(
    profile: str = "auto",
    template_path: Optional[Path] = None,
    output_path: Optional[Path] = None,
    weights_path: Optional[Path] = None,
    td_weights_path: Optional[Path] = None,
) -> BuildConfig:
    root = _workspace_root()
    template_path = template_path or (root / "submission.py")
    output_path = output_path or (root / "submission.py")
    config = resolve_build_config(
        profile=profile,
        weights_path=weights_path,
        td_weights_path=td_weights_path,
    )
    return build_submission_with_config(template_path, output_path, config)


def _main() -> None:
    root = _workspace_root()
    parser = argparse.ArgumentParser(
        description="Build final single-file submission.py from training artifacts."
    )
    parser.add_argument(
        "--profile",
        choices=("auto", "optuna", "td"),
        default="auto",
        help="auto: use TD if available; optuna: force scalar eval; td: force TD eval.",
    )
    parser.add_argument(
        "--template",
        default=str(root / "submission.py"),
        help="Template submission file with BUILD_CONFIG markers.",
    )
    parser.add_argument(
        "--output",
        default=str(root / "submission.py"),
        help="Built single-file agent path (submit this file to Kaggle).",
    )
    parser.add_argument(
        "--weights",
        default=str(root / "agents" / "weights.py"),
        help="Scalar/heatmap artifact path.",
    )
    parser.add_argument(
        "--td-weights",
        default=str(root / "agents" / "td_weights.py"),
        help="TD artifact path.",
    )
    args = parser.parse_args()

    config = build_submission(
        profile=args.profile,
        template_path=Path(args.template),
        output_path=Path(args.output),
        weights_path=Path(args.weights),
        td_weights_path=Path(args.td_weights),
    )

    print(f"[BUILD] profile={args.profile}")
    print(f"[BUILD] output={args.output}")
    print(f"[BUILD] source={config.source}")
    print(
        "[BUILD] scalars="
        f"W_SCORE={_fmt_number(config.w_score)}, "
        f"W_THREAT={_fmt_number(config.w_threat)}, "
        f"W_HMAP={_fmt_number(config.w_hmap)}, "
        f"W_ODD_EVEN={_fmt_number(config.w_odd_even)}"
    )
    print(f"[BUILD] TD enabled={config.td_weights is not None}")


if __name__ == "__main__":
    _main()
