"""Scalar evaluation weights (can be regenerated by evaluate/optimize.py)."""

W_SCORE = 10.0
W_THREAT = 100.0
W_HMAP = 0.3
W_ODD_EVEN = 80.0

POSITION_HEATMAP = [
    [3, 4, 5, 7, 5, 4, 3],
    [4, 6, 8, 10, 8, 6, 4],
    [5, 8, 11, 13, 11, 8, 5],
    [5, 8, 11, 13, 11, 8, 5],
    [4, 6, 8, 10, 8, 6, 4],
    [3, 4, 5, 7, 5, 4, 3],
]
